version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5051:5051"
    depends_on:
      - db
    environment:
      ConnectionStrings__DbContext: 'User ID = postgres;Password=MySecretPassword!;Server=db;Port=5432;Database=GetTogetherDB;Integrated Security=true;Pooling=true'

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MySecretPassword!
      POSTGRES_DB: GetTogetherDB
    ports:
      - "5432:5432"